### ISSUE TITLE
Unable to Add Platform 

### ISSUE THREAD

**Issue by kundanSingh11** [apache/cordova-plugman#110]
I am getting this error when ever i am trying to add a platform by 

`plugman platform add --platform_name android`

```
(node:17948) UnhandledPromiseRejectionWarning: Error: platform: true not yet supported
    at Object.add (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\platform.js:51:35)
    at Object.module.exports [as platform] (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\platform_operation.js:23:38)
    at Object.platform (E:\cordova-plugman\node_modules\cordova-lib\src\plugman\plugman.js:153:17)
    at Object.<anonymous> (E:\cordova-plugman\main.js:87:42)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
(node:17948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by raphinesse** [comment]
This should probably be fixed by #109

**Comment by kundanSingh11** [comment]
Yes it worked. I tried your solution but still getting 
plugin id="true" version="true"

**Comment by parasappafluke** [comment]
When can we expect a new release of plugman?

**Comment by raphinesse** [comment]
@parasappafluke Yes, a release with a fix will be made once it is ready.

**Comment by raphinesse** [comment]
@kundanSingh11
> Yes it worked. I tried your solution but still getting
> plugin id="true" version="true"

This is actually a separate bug, as I just discovered

**Comment by raphinesse** [comment]
Plugman v3.0.1 should fix both of these problems.
